"""fix model

Revision ID: 5b70274179f9
Revises: b5d46d947e0e
Create Date: 2024-07-07 23:39:47.926438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b70274179f9'
down_revision: Union[str, None] = 'b5d46d947e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedbacks_id', table_name='feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###
